# Generated by Django 3.0 on 2021-03-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_kycverification_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='id_number',
        ),
    ]
